### PR TITLE
Add Tax Settings for items

### PR DESCRIPTION
**Pull request by LuBuss**
Added into settings
- Tax Included Toggle
- Tax Rate Input

Add to checkout and checkout success
- Tax and Tax (Included)

Tax Calculation is from all items when generating and updating invoice.

### CODE REVIEW

**Comment by LuBuss** [comment]
image
image
image
image

**Comment by tomerBZ** [comment]
is this safe to merge?

**Comment by LuBuss** [comment]
This cannot be merged due to conflicts, I will try to take a look at it over the weekend.

**Comment by tomerBZ** [comment]
Not merged?

**Pull request closed without merging**
