### PR TITLE
Deno

### PR DESCRIPTION
**Pull request by Himadu2000**

### CODE REVIEW

**Comment by capfsb** [comment]
I think deno migrate is so early. Now deno is 1.0 version, developers has not experience with it. Api of deno easy can change. Its look like bad idea. My opinion - stay on node + tsc. We can migrate later when deno stay more stable.

**Review by capfsb — COMMENTED** [review]
I think deno migrate is so early. Now deno is 1.0 version, developers has not experience with it. Api of deno easy can change. Its look like bad idea. My opinion - stay on node + tsc. We can migrate later when deno stay more stable.

**Comment by Himadu2000** [comment]
> I think deno migrate is so early. Now deno is 1.0 version, developers has not experience with it. Api of deno easy can change. Its look like bad idea. My opinion - stay on node + tsc. We can migrate later when deno stay more stable.

Well we can keep in a branch or new repo until it become more stable. Don't you think? And until that we can switch between deno and node easily anyway. And we only have to fix typescript errors anyway...

**Comment by capfsb** [comment]
Yes we can keep separate branch. But i see this huge diff, and its not look like "easily switch between node/deno".

Problems in this code
1. changing 'module' to 'module.ts' or 'module/index.ts'
2. use deno.land for modules. (example - bcrypt). Node cant work with deno.land and URL-dependencies

Also many developers dont know how works with deno, and we lose potential comrades if we migrate

**Comment by Himadu2000** [comment]
> Yes we can keep separate branch. But i see this huge diff, and its not look like "easily switch between node/deno".
> 
> Problems in this code
> 
> 1. changing 'module' to 'module.ts' or 'module/index.ts'
> 2. use deno.land for modules. (example - bcrypt). Node cant work with deno.land and URL-dependencies
> 
> Also many developers dont know how works with deno, and we lose potential comrades if we migrate

Don't worry keep the checked till it's finished, the problem is the typescript errors, which I need some man power of fixing and because it's only typescript nothing fancy you may be able to help...

**Pull request closed without merging**
