### PR TITLE
add a translate to pt_BR

### PR DESCRIPTION
**Pull request by omurilo**
Hello friends, i'm a Brazilian native and i make a good translation for the project to my language (pt_BR). I have a specified use for him and i'll got share for the community.

And i make four new lines in en.json, reason the add more inputs i18n for the system. (In my project i used for translate form of paypal).

Thanks a lot and we have a force.

### CODE REVIEW

**Review by ngoyal16 — COMMENTED** [review]
theme locales are moved to cezerin2-store. please create a pull request there...  for theme part..

**Comment by omurilo** [comment]
Ok, and locales with folder cezerin2/locales ?

> theme locales are moved to cezerin2-store. please create a pull request there... for theme part..

**Comment by ngoyal16** [comment]
Let me check and update you

**Comment by ngoyal16** [comment]
Remove theme/locals and commit again

**Comment by omurilo** [comment]
@ngoyal16 Hello friend, i push new commit in the project.

**Comment by ngoyal16** [comment]
@murilokaos seems good to go... 

suggest giving a pull request to cezerin2-admin for this pt_BR-Translate in admin/locals

**Pull request merged**
