### PR TITLE
nginx setup

### PR DESCRIPTION
**Pull request by lortschi**

### CODE REVIEW

**Review by vamcart — COMMENTED** [review]
This config from original cezerin

And it's not good for separated apps.

We don't have /admin folder for admin app.

**Comment by lortschi** [comment]
@vamcart this is for the correct (SSL) https:// server nginx setting and it should also work with multiple repo. I just extended the default document. The default has not all setting for ssl nginx in it.

**Comment by vamcart** [comment]
I see /admin folders in setttings.
This doesn't work in separated apps.

        location /admin {
                alias /home/admin/web/yourdomain/public_html/public/admin/;
                try_files /index.html /index.html;
        }

etc...

server settings for admin app removed.

**Comment by lortschi** [comment]
@vamcart yes that could be variable and deponds on multi or mono ...but all other setups are the right way. Otherwise you can not run Cezerin on SSL. I am running it now on VS with SSL and suffered 2 days long to set up correctly.

**Comment by vamcart** [comment]
With this config you can't run admin app.

Default config is from demo.cezerin.net

Maybe just take default config and just add ssl settings.

Do not remove admmin settings, do not add /admin folders.

**Review by vamcart — COMMENTED** [review]
location /admin {
                alias /var/www/cezerin/public/admin/;
                            try_files /index.html /index.html;
        }
        location /admin-assets/ {
                alias /var/www/cezerin/public/admin-assets/;
        }

This code do not required in cezerin2.

root /var/www/cezerin/public/content; 

must be
root /var/www/cezerin2/public/content;


alias /var/www/cezerin/theme/assets/; is not corrent

root /var/www/cezerin/theme/assets/; 

in /sw.js is not correct.

 location /admin {
                alias /home/admin/web/yourdomain/public_html/public/admin/;
                try_files /index.html /index.html;
        }

is not required


 location /admin-assets/ {
                alias /home/admin/web/yourdomain/public_html/public/admin-assets/;
        }

is not required

What is the path ?!

/home/admin/web/yourdomain/public_html/theme/assets/;

We have another path in DOCS - cezerin.org/docs


What is the line -     include /home/admin/conf/web/snginx.yourdomain.conf*;


?!

**Comment by vamcart** [comment]
https://cezerin.org/docs/#/deploy-on-web-nginx

Default config listed here.

Looks like we need working copy.

Just copy config from docs and you have working site.

With this changes that you suggesting we can't start working copy cezerin on the web

**Pull request closed without merging**
