### PR TITLE
Support S3 Assets #35

### PR DESCRIPTION
**Pull request by LuBuss**
Add additional configuration that allows the developer to use S3 Assets.

Note. There is no image resizing on S3 Assets, A few options:

- https://aws.amazon.com/blogs/networking-and-content-delivery/resizing-images-with-amazon-cloudfront-lambdaedge-aws-cdn-blog/
- Add Nginx proxy in S3 (can be done in Docker-proxy)

### CODE REVIEW

**Review by vamcart — APPROVED** [review]

**Comment by ngoyal16** [comment]
is this handle both S3 and and local storage?

**Comment by LuBuss** [comment]
The user can select either local or s3.
This is done by setting `assetServer.type:` to either `'local'` or `'s3'`

**Comment by ngoyal16** [comment]
it's good that we can store now files to s3. but now the question become how we can server files from s3 to website.. using same server or allowing cloud-front too?

if cloud-front then how we will resize the image.

**Comment by LuBuss** [comment]
If you use nginx as a proxy that is easy, though if you want to keep it with AWS we will need to create a lambda to do that.

**Comment by ngoyal16** [comment]
we have to create that in cezerin-scripts.

**Pull request merged**
